name: Deploy to VPS on Testing Branch

on:
  push:
    branches: [ testing ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code (for reference)
        uses: actions/checkout@v3
        with:
          ref: testing

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            DEPLOY_DIR="/home/deploy/nuxt-app"
            # If the deployment directory doesn't exist, clone the repo
            if [ ! -d "$DEPLOY_DIR" ]; then
              git clone https://github.com/<your-username>/<your-repo>.git "$DEPLOY_DIR"
            fi
            cd "$DEPLOY_DIR"
            git fetch origin
            git checkout testing
            git pull origin testing
            docker-compose down
            docker-compose up -d --build
